language: python
python:
    - "2.7"
    - "3.6"

deploy:
    # test pypi
  - provider: pypi
    distributions: sdist bdist_wheel
    server: https://testpypi.python.org/pypi
    user: "al_kricha"
    password:
      secure: "soE9vc0MUomCgHL+OjCSnPaCB8XxqY23B2UzC3y+PEdNtMYUfOM1yHmV9eB3jIQpk98ylvqAflcwfsWVDNoGdq7NK55NuVmpcsl5TXgpIw4xsCKPYwHKpKh8marAmTxcVPieilYi5Bbi+3bPOxBdiz+Mashjr1ockbqCphYdwmtKKiTieOIW0v5jaWxGCLg7p0xDdkFmR/OtKfMEE4slva6czZryTpYbGdLJmHBPnKj/z0hnhyCaWQijW4cIn/7Q2SeGQsZUDz5aKc2p9oaiIVMsGKGCQ0nZ2n7SPL03Hk8p2rT+CKGI5LZhyU2YqqzdRZKg1UTvQkEScM5mtsOJu5TYdDNK0UwZ6ldVgnKe/cbT5f9veavoIJsaUC2pDttwWw4SoPWAr3nVTHyTjVvEX1uLGcXPJzWjGwjnYOc8bPmnGHISzN3YKDL/zYRoWAodYnJjlGdfgKb3DuTNckLsubBFtV+eFjGOhVvNv24xVI0/vLKxQ7pCAIObLFxp1GgpiiXUuraxGQtv3z2CVwjWWxu9JUqLrPmH+eA6JYDDi+3XKyVUpTTCg94jjhz6F3kBy4RF0bizsO7s15pfy7ky/ECKAzTJj8g+wNKSDsb7qi3KXVnwOi8KwPqgpVcXBTCjEYLJkk5Rc1bowVeu+xUm4+1WLkpilN9xOuecselyIMI="
    on:
      branch: master
      tags: false

    # production pypi
  - provider: pypi
    distributions: sdist bdist_wheel
    user: "al_kricha"
    password:
      secure: "edny7dWsjPjnpRimULoFeallQXIowoEoIhw1QpbaK42yPg6AXBSfCrSHQolZrOHeqr4zSqcOmOHX+k2s4u3l1crAsZdo+DCdUuXMAfOKWGlRdslL6KXooYVdOTG7B3I50gu4WiYI8/fif0JdBTHOxHc5s3kY15exeRFLXeQhDeEaYt+CR3HO73kc0eE3rkIgL6gzmckLcFxoAciRlub6uZXonMzrAil9aXJ1C/qFHPWmy+NSKdgWOQAswjO/ojucHyRqBWbFNUK3UTOfrECEMdrv2j8bdbQberbP0yUF0Wg+xuCvYk8nE8uUf8Rj/VsizTrZ+jf1mVMcY7sBhqA0AW5I/3tpSAYkRjMk9CI3uoBdS852pAQo1sPo0arBC4n+af/w7gKYMVlDvLAgSEEDOdG2h/baud9EyjuIusNR2HNammwUIw2jorL3iuRN0m9tEqprgZX6lX1SZ6lEOuTNDJ5V5pEfBGS8EPbbdy0cpnGnGrrcRgL+It4YmxBoEpoiko/y5o6moX2bHASQtcib9RugF0ZheyH266ZzU9DIu6ilpxgq9jaILtDmFfiCUGkIsZ0QcwRgxOM8uezaIn7Cvp87dfHAwRiVH0EXNdsutITQsz/BfZEX6ARTWONQEciM/hidnl7CeDsDgWBV3/Ih1LnRT5qmg8C6L0deOMOw+5Q="
    on:
      branch: master
      tags: true